version: '3.4'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    volumes:
      - frontend_volume:/app/result_dist
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend/kos_web_ti
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  ngixn:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_volume:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend

volumes:
  frontend_volume:
    name: "frontend_volume"
